### ISSUE TITLE
Use the `forge:chests/wooden` tag

### ISSUE THREAD

**Issue by WenXin20** [ThatGravyBoat/Ironchests#33]
The forge version of this mod should use the forge block tag `forge:chests/wooden` for compat with mods that adds chests. such as Woodworks, Every Compat, Twilight Forest, etc.

**Comment by ThatGravyBoat** [comment]
The reason I dont do this is because other mods add trapped chests to that tag and it would not make sense for you to be able to lose the trapped chest part if you upgrade so I just don't allow it, if you don't mind that you can add the forge:chests/wooden tag to the ironchests:upgradeable_wooden_chests tag

**Comment by WenXin20** [comment]
Ah, I see. Yeah, I've already made a datapack for it
