### ISSUE TITLE
block hardness

### ISSUE THREAD

**Issue by rrusciguy** [ThatGravyBoat/Ironchests#4]
Through disabling mods, then testing this mod by itself alongside the usual performance mods, I've narrowed the issue down to this mod. I don't know if its the block hardness or the tools (pickaxes) being affected, but while i can mine dirt and such by hand; stone bricks, iron blocks, coal blocks, and smooth stone take forever to break and dont drop anything with iron or even diamond picks when Iron chests: restocked is installed.

mod ver: 2.0.0
mc: 1.18.2
fabric: 0.14.5

**Comment by ThatGravyBoat** [comment]
did you remove any chests from the config?

**Comment by ThatGravyBoat** [comment]
I did push a fix (2.0.1) which should theoretically fix this.

**Comment by rrusciguy** [comment]
I hadn't touched the config at all, even tried deleting and allowing all cfgs to regenerate before beginning the mod disabling method

**Comment by ThatGravyBoat** [comment]
well the reason why you wouldn't have been able to mine stone and stuff would have been because the mineable tag would have broken so that would have been because somehow one of the default chests didn't exist (which was an oversite now fix) so therefore the block didn't exist so it couldn't find it for the tag.
